HAI 1.2
I HAS A VAR ITZ 1
IM IN YR LP UPPIN YR VAR TIL BOTH SAEM VAR AN 101
  BOTH SAEM 0 AN MOD OF VAR AN 3
  O RLY?
    YA RLY
      BOTH SAEM 0 AN MOD OF VAR AN 5
      O RLY?
        YA RLY
          VISIBLE "FIZZBUZZ "
        NO WAI
          VISIBLE "FIZZ "
      OIC
    MEBBE BOTH SAEM 0 AN MOD OF VAR AN 5
      VISIBLE "BUZZ "
    NO WAI
      VISIBLE VAR
  OIC
IM OUTTA YR LP
KTHXBYE
